---
# tasks file for dns
- name: Prepare, build, install and enable {{ service_name }} container
  block:

  - name: Create user for running "{{ service_name }}"
    import_tasks: create_user.yml
    become: true
  - name: Prepare the "{{ service_name }}" build environment
    import_tasks: prepare_build.yml
    become: true
    become_user: "{{ service_user }}"
  - name: Build the "{{ service_name }}" container image
    import_tasks: build.yml
    become: true
    become_user: "{{ service_user }}"
  - name: Clean the "{{ service_name }}" build space
    import_tasks: clean_builddir.yml
    become: true
    become_user: "{{ service_user }}"
  - name: Deploy the "{{ service_name }}" systemd unit
    import_tasks: deploy.yml
    become: true
  - name: Set up port forwarding for "{{ service_name }}"
    import_tasks: port_forward.yml
    become: true
  when: service_state == "present"

- name: Disable and remove the {{ service_name }} container and service
  block:

  - name: Remove the {{ service_name }} service and dependencies
    import_tasks: undeploy.yml
    become: true
  - name: Remove the {{ service_name }} container image
    import_tasks: clean_image.yml
    become: true
    become_user: "{{ service_user }}"

  when: service_state == "absent"



- 
